FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install \
    libuv1-dev libncurses5-dev libncursesw5-dev xz-utils \
    liblzma-dev tk-dev build-essential \
    libreadline-dev libffi-dev libsqlite3-dev \
    zlib1g-dev zlib1g libbz2-dev libssl-dev \
    curl git make llvm wget \
    python3-virtualenv virtualenv python3.8-venv \
    python3-dev python-openssl -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /src
WORKDIR /src
